apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  namespace: albertodt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: albertodt1995/webserver:v1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        configMap:
          name: html-config
          items:
            - key: index.html
              path: index.html