apiVersion: v1
kind: Service
metadata:
  name: webserver
  namespace: albertodt
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 7020
      targetPort: 80
